export const breadcrumbNameMap = {
  "/login": "Login",
  "/register": "Register",
  "/register/complete": "Register Complete",
  "/add-to-cart": "Your Card",
  "/feature-product": "Feature Products",
  "/beer": "Beer",
  "/beer/domestic-beer": "Domestic Beer",
  "/beer/imported-beer": "Imported Beer",
  "/rum": "Rum",
  "/rum/domestic-rum": "Domestic Rum",
  "/rum/imported-rum": "Imported Rum",
  "/vodka": "Vodka",
  "/vodka/domestic-vodka": "Domestic Vodka",
  "/vodka/imported-vodka": "Imported Vodka",
  "/whisky": "Whisky",
  "/whisky/domestic-whisky": "Domestic Whisky",
  "/whisky/imported-whisky": "Imported Whisky",
  "/brandy": "Brandy",
  "/brandy/domestic-brandy": "Domestic Brandy",
  "/brandy/imported-brandy": "Imported Brandy",
  "/wine": "Wine",
  "/wine/domestic-wine": "Domestic Wine",
  "/wine/imported-wine": "Imported Wine",
  "/kodo": "Kodo",
  "/checkout": "Checkout",
  "/history": "Your History",
};
